// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: NonRealTimeData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from NonRealTimeData.proto</summary>
public static partial class NonRealTimeDataReflection {

  #region Descriptor
  /// <summary>File descriptor for NonRealTimeData.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static NonRealTimeDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChVOb25SZWFsVGltZURhdGEucHJvdG8itQMKFERvYm90Tm9uUmVhbFRpbWVE",
          "YXRhEhEKBG5hbWUYASABKAlIAIgBARIPCgJpZBgCIAEoBUgBiAEBEhIKCmhv",
          "bWVQYXJhbXMYAyADKAISGQoRZW5kRWZmZWN0b3JQYXJhbXMYBCADKAISKQoh",
          "am9nSm9pbnRfVmVsb2NpdHlXaXRoQWNjZWxlcmF0aW9uGAUgAygCEi4KJmpv",
          "Z0Nvb3JkaW5hdGVfVmVsb2NpdHlXaXRoQWNjZWxlcmF0aW9uGAYgAygCEi8K",
          "J2pvZ0NvbW1vbl9WZWxvY2l0eVJhdGlvV2l0aEFjY2VsZXJhdGlvbhgHIAMo",
          "AhIpCiFwdHBKb2ludF9WZWxvY2l0eVdpdGhBY2NlbGVyYXRpb24YCCADKAIS",
          "LgomcHRwQ29vcmRpbmF0ZV9WZWxvY2l0eVdpdGhBY2NlbGVyYXRpb24YCSAD",
          "KAISLwoncHRwQ29tbW9uX1ZlbG9jaXR5UmF0aW9XaXRoQWNjZWxlcmF0aW9u",
          "GAogAygCEhUKCGRhdGVUaW1lGAsgASgJSAKIAQFCBwoFX25hbWVCBQoDX2lk",
          "QgsKCV9kYXRlVGltZWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::DobotNonRealTimeData), global::DobotNonRealTimeData.Parser, new[]{ "Name", "Id", "HomeParams", "EndEffectorParams", "JogJointVelocityWithAcceleration", "JogCoordinateVelocityWithAcceleration", "JogCommonVelocityRatioWithAcceleration", "PtpJointVelocityWithAcceleration", "PtpCoordinateVelocityWithAcceleration", "PtpCommonVelocityRatioWithAcceleration", "DateTime" }, new[]{ "Name", "Id", "DateTime" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class DobotNonRealTimeData : pb::IMessage<DobotNonRealTimeData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<DobotNonRealTimeData> _parser = new pb::MessageParser<DobotNonRealTimeData>(() => new DobotNonRealTimeData());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<DobotNonRealTimeData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::NonRealTimeDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DobotNonRealTimeData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DobotNonRealTimeData(DobotNonRealTimeData other) : this() {
    _hasBits0 = other._hasBits0;
    name_ = other.name_;
    id_ = other.id_;
    homeParams_ = other.homeParams_.Clone();
    endEffectorParams_ = other.endEffectorParams_.Clone();
    jogJointVelocityWithAcceleration_ = other.jogJointVelocityWithAcceleration_.Clone();
    jogCoordinateVelocityWithAcceleration_ = other.jogCoordinateVelocityWithAcceleration_.Clone();
    jogCommonVelocityRatioWithAcceleration_ = other.jogCommonVelocityRatioWithAcceleration_.Clone();
    ptpJointVelocityWithAcceleration_ = other.ptpJointVelocityWithAcceleration_.Clone();
    ptpCoordinateVelocityWithAcceleration_ = other.ptpCoordinateVelocityWithAcceleration_.Clone();
    ptpCommonVelocityRatioWithAcceleration_ = other.ptpCommonVelocityRatioWithAcceleration_.Clone();
    dateTime_ = other.dateTime_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DobotNonRealTimeData Clone() {
    return new DobotNonRealTimeData(this);
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 1;
  private readonly static string NameDefaultValue = "";

  private string name_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Name {
    get { return name_ ?? NameDefaultValue; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "name" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasName {
    get { return name_ != null; }
  }
  /// <summary>Clears the value of the "name" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearName() {
    name_ = null;
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 2;
  private readonly static int IdDefaultValue = 0;

  private int id_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Id {
    get { if ((_hasBits0 & 1) != 0) { return id_; } else { return IdDefaultValue; } }
    set {
      _hasBits0 |= 1;
      id_ = value;
    }
  }
  /// <summary>Gets whether the "id" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasId {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "id" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearId() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "homeParams" field.</summary>
  public const int HomeParamsFieldNumber = 3;
  private static readonly pb::FieldCodec<float> _repeated_homeParams_codec
      = pb::FieldCodec.ForFloat(26);
  private readonly pbc::RepeatedField<float> homeParams_ = new pbc::RepeatedField<float>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<float> HomeParams {
    get { return homeParams_; }
  }

  /// <summary>Field number for the "endEffectorParams" field.</summary>
  public const int EndEffectorParamsFieldNumber = 4;
  private static readonly pb::FieldCodec<float> _repeated_endEffectorParams_codec
      = pb::FieldCodec.ForFloat(34);
  private readonly pbc::RepeatedField<float> endEffectorParams_ = new pbc::RepeatedField<float>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<float> EndEffectorParams {
    get { return endEffectorParams_; }
  }

  /// <summary>Field number for the "jogJoint_VelocityWithAcceleration" field.</summary>
  public const int JogJointVelocityWithAccelerationFieldNumber = 5;
  private static readonly pb::FieldCodec<float> _repeated_jogJointVelocityWithAcceleration_codec
      = pb::FieldCodec.ForFloat(42);
  private readonly pbc::RepeatedField<float> jogJointVelocityWithAcceleration_ = new pbc::RepeatedField<float>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<float> JogJointVelocityWithAcceleration {
    get { return jogJointVelocityWithAcceleration_; }
  }

  /// <summary>Field number for the "jogCoordinate_VelocityWithAcceleration" field.</summary>
  public const int JogCoordinateVelocityWithAccelerationFieldNumber = 6;
  private static readonly pb::FieldCodec<float> _repeated_jogCoordinateVelocityWithAcceleration_codec
      = pb::FieldCodec.ForFloat(50);
  private readonly pbc::RepeatedField<float> jogCoordinateVelocityWithAcceleration_ = new pbc::RepeatedField<float>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<float> JogCoordinateVelocityWithAcceleration {
    get { return jogCoordinateVelocityWithAcceleration_; }
  }

  /// <summary>Field number for the "jogCommon_VelocityRatioWithAcceleration" field.</summary>
  public const int JogCommonVelocityRatioWithAccelerationFieldNumber = 7;
  private static readonly pb::FieldCodec<float> _repeated_jogCommonVelocityRatioWithAcceleration_codec
      = pb::FieldCodec.ForFloat(58);
  private readonly pbc::RepeatedField<float> jogCommonVelocityRatioWithAcceleration_ = new pbc::RepeatedField<float>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<float> JogCommonVelocityRatioWithAcceleration {
    get { return jogCommonVelocityRatioWithAcceleration_; }
  }

  /// <summary>Field number for the "ptpJoint_VelocityWithAcceleration" field.</summary>
  public const int PtpJointVelocityWithAccelerationFieldNumber = 8;
  private static readonly pb::FieldCodec<float> _repeated_ptpJointVelocityWithAcceleration_codec
      = pb::FieldCodec.ForFloat(66);
  private readonly pbc::RepeatedField<float> ptpJointVelocityWithAcceleration_ = new pbc::RepeatedField<float>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<float> PtpJointVelocityWithAcceleration {
    get { return ptpJointVelocityWithAcceleration_; }
  }

  /// <summary>Field number for the "ptpCoordinate_VelocityWithAcceleration" field.</summary>
  public const int PtpCoordinateVelocityWithAccelerationFieldNumber = 9;
  private static readonly pb::FieldCodec<float> _repeated_ptpCoordinateVelocityWithAcceleration_codec
      = pb::FieldCodec.ForFloat(74);
  private readonly pbc::RepeatedField<float> ptpCoordinateVelocityWithAcceleration_ = new pbc::RepeatedField<float>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<float> PtpCoordinateVelocityWithAcceleration {
    get { return ptpCoordinateVelocityWithAcceleration_; }
  }

  /// <summary>Field number for the "ptpCommon_VelocityRatioWithAcceleration" field.</summary>
  public const int PtpCommonVelocityRatioWithAccelerationFieldNumber = 10;
  private static readonly pb::FieldCodec<float> _repeated_ptpCommonVelocityRatioWithAcceleration_codec
      = pb::FieldCodec.ForFloat(82);
  private readonly pbc::RepeatedField<float> ptpCommonVelocityRatioWithAcceleration_ = new pbc::RepeatedField<float>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<float> PtpCommonVelocityRatioWithAcceleration {
    get { return ptpCommonVelocityRatioWithAcceleration_; }
  }

  /// <summary>Field number for the "dateTime" field.</summary>
  public const int DateTimeFieldNumber = 11;
  private readonly static string DateTimeDefaultValue = "";

  private string dateTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string DateTime {
    get { return dateTime_ ?? DateTimeDefaultValue; }
    set {
      dateTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "dateTime" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasDateTime {
    get { return dateTime_ != null; }
  }
  /// <summary>Clears the value of the "dateTime" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearDateTime() {
    dateTime_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as DobotNonRealTimeData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(DobotNonRealTimeData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Name != other.Name) return false;
    if (Id != other.Id) return false;
    if(!homeParams_.Equals(other.homeParams_)) return false;
    if(!endEffectorParams_.Equals(other.endEffectorParams_)) return false;
    if(!jogJointVelocityWithAcceleration_.Equals(other.jogJointVelocityWithAcceleration_)) return false;
    if(!jogCoordinateVelocityWithAcceleration_.Equals(other.jogCoordinateVelocityWithAcceleration_)) return false;
    if(!jogCommonVelocityRatioWithAcceleration_.Equals(other.jogCommonVelocityRatioWithAcceleration_)) return false;
    if(!ptpJointVelocityWithAcceleration_.Equals(other.ptpJointVelocityWithAcceleration_)) return false;
    if(!ptpCoordinateVelocityWithAcceleration_.Equals(other.ptpCoordinateVelocityWithAcceleration_)) return false;
    if(!ptpCommonVelocityRatioWithAcceleration_.Equals(other.ptpCommonVelocityRatioWithAcceleration_)) return false;
    if (DateTime != other.DateTime) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasName) hash ^= Name.GetHashCode();
    if (HasId) hash ^= Id.GetHashCode();
    hash ^= homeParams_.GetHashCode();
    hash ^= endEffectorParams_.GetHashCode();
    hash ^= jogJointVelocityWithAcceleration_.GetHashCode();
    hash ^= jogCoordinateVelocityWithAcceleration_.GetHashCode();
    hash ^= jogCommonVelocityRatioWithAcceleration_.GetHashCode();
    hash ^= ptpJointVelocityWithAcceleration_.GetHashCode();
    hash ^= ptpCoordinateVelocityWithAcceleration_.GetHashCode();
    hash ^= ptpCommonVelocityRatioWithAcceleration_.GetHashCode();
    if (HasDateTime) hash ^= DateTime.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasName) {
      output.WriteRawTag(10);
      output.WriteString(Name);
    }
    if (HasId) {
      output.WriteRawTag(16);
      output.WriteInt32(Id);
    }
    homeParams_.WriteTo(output, _repeated_homeParams_codec);
    endEffectorParams_.WriteTo(output, _repeated_endEffectorParams_codec);
    jogJointVelocityWithAcceleration_.WriteTo(output, _repeated_jogJointVelocityWithAcceleration_codec);
    jogCoordinateVelocityWithAcceleration_.WriteTo(output, _repeated_jogCoordinateVelocityWithAcceleration_codec);
    jogCommonVelocityRatioWithAcceleration_.WriteTo(output, _repeated_jogCommonVelocityRatioWithAcceleration_codec);
    ptpJointVelocityWithAcceleration_.WriteTo(output, _repeated_ptpJointVelocityWithAcceleration_codec);
    ptpCoordinateVelocityWithAcceleration_.WriteTo(output, _repeated_ptpCoordinateVelocityWithAcceleration_codec);
    ptpCommonVelocityRatioWithAcceleration_.WriteTo(output, _repeated_ptpCommonVelocityRatioWithAcceleration_codec);
    if (HasDateTime) {
      output.WriteRawTag(90);
      output.WriteString(DateTime);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasName) {
      output.WriteRawTag(10);
      output.WriteString(Name);
    }
    if (HasId) {
      output.WriteRawTag(16);
      output.WriteInt32(Id);
    }
    homeParams_.WriteTo(ref output, _repeated_homeParams_codec);
    endEffectorParams_.WriteTo(ref output, _repeated_endEffectorParams_codec);
    jogJointVelocityWithAcceleration_.WriteTo(ref output, _repeated_jogJointVelocityWithAcceleration_codec);
    jogCoordinateVelocityWithAcceleration_.WriteTo(ref output, _repeated_jogCoordinateVelocityWithAcceleration_codec);
    jogCommonVelocityRatioWithAcceleration_.WriteTo(ref output, _repeated_jogCommonVelocityRatioWithAcceleration_codec);
    ptpJointVelocityWithAcceleration_.WriteTo(ref output, _repeated_ptpJointVelocityWithAcceleration_codec);
    ptpCoordinateVelocityWithAcceleration_.WriteTo(ref output, _repeated_ptpCoordinateVelocityWithAcceleration_codec);
    ptpCommonVelocityRatioWithAcceleration_.WriteTo(ref output, _repeated_ptpCommonVelocityRatioWithAcceleration_codec);
    if (HasDateTime) {
      output.WriteRawTag(90);
      output.WriteString(DateTime);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasName) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (HasId) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
    }
    size += homeParams_.CalculateSize(_repeated_homeParams_codec);
    size += endEffectorParams_.CalculateSize(_repeated_endEffectorParams_codec);
    size += jogJointVelocityWithAcceleration_.CalculateSize(_repeated_jogJointVelocityWithAcceleration_codec);
    size += jogCoordinateVelocityWithAcceleration_.CalculateSize(_repeated_jogCoordinateVelocityWithAcceleration_codec);
    size += jogCommonVelocityRatioWithAcceleration_.CalculateSize(_repeated_jogCommonVelocityRatioWithAcceleration_codec);
    size += ptpJointVelocityWithAcceleration_.CalculateSize(_repeated_ptpJointVelocityWithAcceleration_codec);
    size += ptpCoordinateVelocityWithAcceleration_.CalculateSize(_repeated_ptpCoordinateVelocityWithAcceleration_codec);
    size += ptpCommonVelocityRatioWithAcceleration_.CalculateSize(_repeated_ptpCommonVelocityRatioWithAcceleration_codec);
    if (HasDateTime) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(DateTime);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(DobotNonRealTimeData other) {
    if (other == null) {
      return;
    }
    if (other.HasName) {
      Name = other.Name;
    }
    if (other.HasId) {
      Id = other.Id;
    }
    homeParams_.Add(other.homeParams_);
    endEffectorParams_.Add(other.endEffectorParams_);
    jogJointVelocityWithAcceleration_.Add(other.jogJointVelocityWithAcceleration_);
    jogCoordinateVelocityWithAcceleration_.Add(other.jogCoordinateVelocityWithAcceleration_);
    jogCommonVelocityRatioWithAcceleration_.Add(other.jogCommonVelocityRatioWithAcceleration_);
    ptpJointVelocityWithAcceleration_.Add(other.ptpJointVelocityWithAcceleration_);
    ptpCoordinateVelocityWithAcceleration_.Add(other.ptpCoordinateVelocityWithAcceleration_);
    ptpCommonVelocityRatioWithAcceleration_.Add(other.ptpCommonVelocityRatioWithAcceleration_);
    if (other.HasDateTime) {
      DateTime = other.DateTime;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Name = input.ReadString();
          break;
        }
        case 16: {
          Id = input.ReadInt32();
          break;
        }
        case 26:
        case 29: {
          homeParams_.AddEntriesFrom(input, _repeated_homeParams_codec);
          break;
        }
        case 34:
        case 37: {
          endEffectorParams_.AddEntriesFrom(input, _repeated_endEffectorParams_codec);
          break;
        }
        case 42:
        case 45: {
          jogJointVelocityWithAcceleration_.AddEntriesFrom(input, _repeated_jogJointVelocityWithAcceleration_codec);
          break;
        }
        case 50:
        case 53: {
          jogCoordinateVelocityWithAcceleration_.AddEntriesFrom(input, _repeated_jogCoordinateVelocityWithAcceleration_codec);
          break;
        }
        case 58:
        case 61: {
          jogCommonVelocityRatioWithAcceleration_.AddEntriesFrom(input, _repeated_jogCommonVelocityRatioWithAcceleration_codec);
          break;
        }
        case 66:
        case 69: {
          ptpJointVelocityWithAcceleration_.AddEntriesFrom(input, _repeated_ptpJointVelocityWithAcceleration_codec);
          break;
        }
        case 74:
        case 77: {
          ptpCoordinateVelocityWithAcceleration_.AddEntriesFrom(input, _repeated_ptpCoordinateVelocityWithAcceleration_codec);
          break;
        }
        case 82:
        case 85: {
          ptpCommonVelocityRatioWithAcceleration_.AddEntriesFrom(input, _repeated_ptpCommonVelocityRatioWithAcceleration_codec);
          break;
        }
        case 90: {
          DateTime = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Name = input.ReadString();
          break;
        }
        case 16: {
          Id = input.ReadInt32();
          break;
        }
        case 26:
        case 29: {
          homeParams_.AddEntriesFrom(ref input, _repeated_homeParams_codec);
          break;
        }
        case 34:
        case 37: {
          endEffectorParams_.AddEntriesFrom(ref input, _repeated_endEffectorParams_codec);
          break;
        }
        case 42:
        case 45: {
          jogJointVelocityWithAcceleration_.AddEntriesFrom(ref input, _repeated_jogJointVelocityWithAcceleration_codec);
          break;
        }
        case 50:
        case 53: {
          jogCoordinateVelocityWithAcceleration_.AddEntriesFrom(ref input, _repeated_jogCoordinateVelocityWithAcceleration_codec);
          break;
        }
        case 58:
        case 61: {
          jogCommonVelocityRatioWithAcceleration_.AddEntriesFrom(ref input, _repeated_jogCommonVelocityRatioWithAcceleration_codec);
          break;
        }
        case 66:
        case 69: {
          ptpJointVelocityWithAcceleration_.AddEntriesFrom(ref input, _repeated_ptpJointVelocityWithAcceleration_codec);
          break;
        }
        case 74:
        case 77: {
          ptpCoordinateVelocityWithAcceleration_.AddEntriesFrom(ref input, _repeated_ptpCoordinateVelocityWithAcceleration_codec);
          break;
        }
        case 82:
        case 85: {
          ptpCommonVelocityRatioWithAcceleration_.AddEntriesFrom(ref input, _repeated_ptpCommonVelocityRatioWithAcceleration_codec);
          break;
        }
        case 90: {
          DateTime = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
